/* Generated from Emperia-Server/protocol/realtime-contract.schema.json. */
/* Do not edit this file directly. */

export const PROTOCOL_SCHEMA_SHA256 = "b1f2bdcdfa13e96ee0540e95ed4ec2c81e024942ad34058a10fb742892b020a8";

export const ITEM_SLOT_TYPES = [
  "head",
  "body",
  "legs",
  "feet",
  "left-hand",
  "right-hand",
  "hand",
  "two-handed",
  "ring",
  "necklace",
  "backpack",
  "belt",
  "ammo",
  "quiver",
  "rope",
  "shovel",
  "pick",
  "knife",
  "machete",
  "fishingRod",
  "potion",
  "food",
  "rune",
  "key",
  "torch",
  "pet",
  "cape",
  "mask",
] as const;
export type ItemSlotType = typeof ITEM_SLOT_TYPES[number];

export function encodeItemSlotType(slotType: string): number {
  const index = ITEM_SLOT_TYPES.indexOf(slotType as ItemSlotType);
  if (index < 0) throw new Error(`Unknown item slot type "${slotType}"`);
  return index + 1;
}

export function decodeItemSlotType(code: number): ItemSlotType {
  const slotType = ITEM_SLOT_TYPES[code - 1];
  if (!slotType) throw new Error(`Unknown item slot type code ${code}`);
  return slotType;
}
export const EXCLUSIVE_SLOT_CATEGORY_CODE_BY_TYPE: Readonly<Record<ItemSlotType, number>> = Object.freeze({"head":10,"body":11,"legs":12,"feet":13,"left-hand":14,"right-hand":15,"hand":16,"two-handed":17,"ring":18,"necklace":19,"backpack":20,"belt":21,"ammo":29,"quiver":22,"rope":1,"shovel":2,"pick":3,"knife":4,"machete":7,"fishingRod":5,"potion":6,"food":23,"rune":24,"key":25,"torch":30,"pet":31,"cape":27,"mask":28});
export const EXCLUSIVE_SLOT_TYPE_BY_CATEGORY_CODE: Readonly<Record<number, ItemSlotType>> = Object.freeze({"1":"rope","2":"shovel","3":"pick","4":"knife","5":"fishingRod","6":"potion","7":"machete","10":"head","11":"body","12":"legs","13":"feet","14":"left-hand","15":"right-hand","16":"hand","17":"two-handed","18":"ring","19":"necklace","20":"backpack","21":"belt","22":"quiver","23":"food","24":"rune","25":"key","27":"cape","28":"mask","29":"ammo","30":"torch","31":"pet"});
export const ITEM_CATEGORY_CODE_BY_TYPE = Object.freeze({"rope":1,"shovel":2,"pick":3,"knife":4,"fishingRod":5,"potion":6,"machete":7,"creatureProduct":32});
export type ItemCategoryType = keyof typeof ITEM_CATEGORY_CODE_BY_TYPE;
export const ITEM_CATEGORY_TYPE_BY_CODE: Readonly<Record<number, ItemCategoryType>> = Object.freeze({"1":"rope","2":"shovel","3":"pick","4":"knife","5":"fishingRod","6":"potion","7":"machete","32":"creatureProduct"});
