/* Generated from Emperia-Server/protocol/realtime-contract.schema.json. */
/* Do not edit this file directly. */

export const PROTOCOL_SCHEMA_SHA256 = "7c2f56647bf5cbb4e87039803087a14c2de1891f5bd597d584d81ba8d17a12be";

export const ITEM_SLOT_TYPES = [
  "head",
  "body",
  "legs",
  "feet",
  "left-hand",
  "right-hand",
  "hand",
  "two-handed",
  "ring",
  "necklace",
  "backpack",
  "belt",
  "ammo",
  "quiver",
  "rope",
  "shovel",
  "pick",
  "knife",
  "machete",
  "fishingRod",
  "potion",
  "food",
  "rune",
  "key",
  "torch",
  "pet",
] as const;
export type ItemSlotType = typeof ITEM_SLOT_TYPES[number];

export function encodeItemSlotType(slotType: string): number {
  const index = ITEM_SLOT_TYPES.indexOf(slotType as ItemSlotType);
  if (index < 0) throw new Error(`Unknown item slot type "${slotType}"`);
  return index + 1;
}

export function decodeItemSlotType(code: number): ItemSlotType {
  const slotType = ITEM_SLOT_TYPES[code - 1];
  if (!slotType) throw new Error(`Unknown item slot type code ${code}`);
  return slotType;
}
