/* Generated by Emperia-Server/scripts/build/generate-protocol-contracts.mjs. */
/* Do not edit directly; edit Emperia-Server/protocol/realtime-contract.schema.json. */

export const MATERIAL_MASK_RGB_METAL = 5088255;
export const MATERIAL_MASK_RGB_LEATHER = 16751165;
export const MATERIAL_MASK_RGB_CLOTH = 14179583;
export const MATERIAL_MASK_RGB_WOOD = 6669414;
